
FROM qcdis/miniconda3 AS build
COPY sayhi-group-7-environment.yaml .
RUN conda env update -n venv -f sayhi-group-7-environment.yaml
RUN conda-pack -n venv -o /tmp/env.tar && \
    mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
    rm /tmp/env.tar
RUN /venv/bin/conda-unpack

FROM python:3.11-slim-bullseye AS runtime
RUN apt update -y && apt upgrade -y && apt install jq -y
COPY --from=build /venv /venv
COPY sayhi-group-7.py .

