FROM continuumio/miniconda3:22.11.1 AS build
COPY download-knmi-v30-berend-environment.yaml .
RUN conda env update -n venv -f download-knmi-v30-berend-environment.yaml
RUN conda install -c conda-forge conda-pack
RUN conda-pack -n venv -o /tmp/env.tar && \
    mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
    rm /tmp/env.tar
RUN /venv/bin/conda-unpack

FROM qcdis/python-vol2bird AS runtime
RUN apt update -y && apt upgrade -y && apt install jq -y
COPY --from=build /venv /venv
COPY download-knmi-v30-berend.py .

